### ISSUE TITLE
Error building with lualatex

### ISSUE THREAD

**Issue by tbm** [fmarotta/kaobook#110]
#23 is closed so I thought kaobook would work with lualatex but I'm getting errors.

First I get:

```
! LaTeX Error: Unknown option `force' for package `filehook'.
```

After I remove `[force]`, I get:

```
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty)

! LaTeX Error: Command \dddot already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.733    \hbox{\normalfont ...}\vss}}}}
                                     
? 
```

I'm on Debian 10 which has LuaTeX 2018.20190227-2.

CC @yordiak

**Comment by yordiak** [comment]
_Recommendation: I would suggest to stick to pdflatex, If your document isn't multilingual_

I would like to mention the following: 
(1) It is always useful to provide a mwe in order to be clearer which the actual problem is
(2) I managed to solve the problem by modifying the kao.sty file and especially, by removing the section upon fonts/language. Thus, I made lualatex to work by loading the necessary packages in my document's preamble. This decision was made (to change that file) because I needed better support for both text and maths.
(3) Your luallatex version seems to be old. I know that Debian -due to stability issues- does not update regularly its packages. So, I would firstly recommend to update your lualatex engine (by updating your tex distro)

**Comment by fmarotta** [comment]
Thanks for reporting this. I did not notice these errors because they are not present with an updated (2020) version of lualatex. So unless you really have to use the 2018 version, the simplest thing would be to update your tex distribution.

**Comment by tbm** [comment]
I don't really use lualatex. I just wanted to report in case it's easy to fix.

Closing.
