### ISSUE TITLE
Recommended Steps for Custom Paper Size

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#111]
Different publishers have different paper sizes that they print on. For example, one is asking me if the book can fit on 7 in x 10 in. Are there recommended steps for getting kaobook to work (e.g. tuning whatever parameters are necessary to look good) on non-standard paper sizes that aren't already easily supported by class options such as "b5paper"?

**Comment by fmarotta** [comment]
For the paper sizes that I have tried so far, simply stretching or shrinking the horizontal and vertical dimensions to match the paper size works pretty well. I'd say that the best way to fit the book on a custom paper size is to add a new class option (it's just one line of code!) and then use that option.

But first, in any case, you should compute the ratio between your custom paper width and the A4 paper width (8-1/4 in), and the ratio between your custom paper height and the A4 paper height (11-3/4 in). For example, if my calculations are correct, for the paper size you mentioned in the question the ratios would be 0.848 and 0.851, respectively. Then, if you just add

```
\@ifclasswith{\@baseclass}{mypapersize}{\setlength{\hscale}{0.848mm}\setlength{\vscale}{0.851mm}}{}
```

in the file `styles/kao.sty`, then you can use kaobook with the class option "mypapersize", and it should look good on 7x10 in paper. Please note that `\hscale` and `\vscale` should be specified in millimeters.

Alternatively, if you don't want to define a new class option, you can just hard-code the following snippet somewhere in kaobook's class files

```
\setlength{\hscale}{0.848mm}
\setlength{\vscale}{0.851mm}
```

I don't think that setting this in main.tex would work, because some lengths are defined even before starting to read the main.tex.
