### ISSUE TITLE
Include page number in footer on pages with \setchapterimage

### ISSUE THREAD

**Issue by tbm** [fmarotta/kaobook#131]
This might be more of a support request, but I think this is of general interest so maybe you can add something to the documentation.

On pages that use `\setchapterimage`, the page number is not shown anywhere.  I think it makes sense to show it in the footer on such pages (centered).

It's not clear how to do that.  When I applied some code online, the ` \setchapterimage` image disappeared.

Can you add some examples to the docs about this?

(Maybe you have an even better idea on how to include the page number which this kind of layout.)

**Comment by AlexanderZeilmann** [comment]
I think this has nothing to do with `\setchapterimage` but with the fact that it is the first page of a chapter. On normal pages, the page number is shown somewhere at the top, but on the first page of the chapter, there is no place for this.
This is however not only the case with `kaobook`, but with many other templates and books as well.

Now there are basically two solutions:
* Do not put a page number on the first chapter page at all.
* Put the page number somewhere, where it normally is not, i.e., in the footer.

It is only a matter of taste what to choose. I am more for putting no page numbers on those pages, because if the number is in the "wrong" position it is not really more helpful than having no number at all.

----

That said, here is a short snippet of how to do this:

Somewhere in the preamble
```
\usepackage{fancyhdr}
\fancyhead{}
\fancyfoot{}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0}
```

In the document append  `\thispagestyle{fancy}` to the `\chapter` like this:
```
\chapter{Some Name}\thispagestyle{fancy}
```

I did not extensively test this, so I hope it is not breaking too much other things.

**Comment by tbm** [comment]
@AlexanderZeilmann thanks for your information and sorry for the delay.

I've tried this but unfortunately it doesn't seem to work.  I get:

```
Class scrbook Warning: Usage of package `fancyhdr' together
(scrbook)              with a KOMA-Script class is not recommended.
(scrbook)              I'd suggest to use 
(scrbook)              package `scrlayer' or `scrlayer-scrpage', because
(scrbook)              they support KOMA-Script classes.
...

! LaTeX Error: Command \chead already defined.
               Or name \end... illegal, see p.192 of the manual.
```

This is triggered by simply:

```
\usepackage{fancyhdr}
```

**Comment by fmarotta** [comment]
Hi, @AlexanderZeilmann is right: the page number is not displayed in pages where a new chapter begins. However, fancyhdr is not compatible with KomaScript because the latter has its own mechanism to specify page styles. You could try with something like this (to be put in the preamble):

```
\newpagestyle{mystylewithpagenumber}{%
  {}%
  {}%
  {}%
}{%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
}
\renewcommand*{\chapterpagestyle}{mystylewithpagenumber}
```

The syntax for \defpagestyle is as follows.
```
\defpagestyle{<stylename>}{<header spec>}{<footer spec>}
```
in particular
```
{<header spec>} = {%
  {<spec for the left page in two-side mode>}%
  {<spec for the right page in two-side mode>}%
  {<spec for the page in one-side mode>}%
}
```
and the same goes for the footer.

PS
I haven't had time to test it, sorry!

**Comment by AlexanderZeilmann** [comment]
Ahh, @fmarotta beat me in answering it 😄 

Let me just add that the following in the preamble is enough:
```
\renewcommand{\chapterpagestyle}{pagenum.scrheadings}
```

(The `pagenum.scrheadings` style is, however, undocumented.)

**Comment by fmarotta** [comment]
Oh, that's great, didn't know about it :)

**Comment by tbm** [comment]
The solution from @fmarotta works (don't see any problems so far).

I'm not sure how to interpret @AlexanderZeilmann's comments.  Just

```
\renewcommand{\chapterpagestyle}{pagenum.scrheadings}
```
didn't do anything as far as I can tell.

**Comment by AlexanderZeilmann** [comment]
Hmm, that's odd...

Here is my entire code:
```
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}

\renewcommand{\chapterpagestyle}{pagenum.scrheadings}

\begin{document}

\title{Bug Report}
\author{Author}
\date{\today}

\frontmatter

\KOMAoptions{twoside=semi}
\maketitle
\KOMAoptions{twoside=false}

\mainmatter
\setchapterstyle{kao}

\chapter{First Chapter}
\blindtext

\end{document}
```

For me, this adds the page number on the first page of each chapter.

The `pagenum.scrheadings` style is defined here: https://github.com/fmarotta/kaobook/blob/006e62b679176eaa102d2dff09f813f801494a01/kao.sty#L235-L244

Btw. sorry that the fancyhdr solution is not working any longer :-/

**Comment by fmarotta** [comment]
Ahh, it seems that I had already redefined the `pagenum.scrheadings` style and completely forgotten about it. By the way, I think my code is bugged, because in one-side mode the page number should not be shown. I will try to replace it with
```
\newpagestyle{pagenum.scrheadings}{%
  {}%
  {}%
  {}%
}{%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
 {\parbox[b][][c]{\textwidth}{\thepage}}%
}
```

**Comment by tbm** [comment]
Thanks for your help @AlexanderZeilmann and @fmarotta!

**Comment by fmarotta** [comment]
Sorry to add more irons in the fire, but I have now defined two page styles, one called `pagenum.scrheadings` and one called `centeredpagenum.scrheadings`. Both add the page number to the footer, but the former aligns it to the corner of the page, while the latter centers it. You can activate either of them by adding, e.g., `\renewcommand{\chapterpagestyle}{pagenum.scrheadings}` to the preamble of your main.tex.

**Comment by tbm** [comment]
Thanks, `centeredpagenum.scrheadings` does exactly what I want.
