### ISSUE TITLE
kaobiblio is required to compile without errors

### ISSUE THREAD

**Issue by AlexanderZeilmann** [fmarotta/kaobook#133]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description
I expected that all required definitions are set up with the statement `\documentclass{kaobook}` and that the files `kaobiblio`, `kaotheorems` and `kaorefs` are optional.
However, currently `kaobiblio` is required to compile the file without errors.

**Expected behavior:** 
The file below compiles without error.

**Actual behavior:** 
Compiling the document below without `\usepackage{kaobiblio}` yields the following error:
```
./paper.aux:27: Undefined control sequence.
l.27 \abx@aux@refcontext
                                          {none/global//global/global}
```

### Minimal Working Example
```
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
%\usepackage{kaobiblio}   % Uncommenting this line fixes the error.
\usepackage{kaotheorems}
\usepackage{kaorefs}

\begin{document}
\blindtext
\end{document}
```

**Comment by fmarotta** [comment]
Hi, I think this error occurs in the following situation:
1. you compile the document *with* kaobiblio
2. you remove kaobiblio and recompile

However, in this case the error goes away if you ignore the error (just press enter when the compilation halts) and compile a second time. Alternatively, try deleting the auxiliary files (everything except the .tex & .bib) before recompiling.

This issue is probably related to the babel package and the fact that it saves some macros somewhere in the auxiliary files. In fact I remember an error like that when switching between `pdflatex` and `xelatex` compilation (pdflatex used babel, xelatex uses polyglossia). Anyway, in all cases, compiling twice in a row should solve the problem. At least on my machine it works. Please let me know if there is something deeper to it :)

**Comment by AlexanderZeilmann** [comment]
Ah, I guess you are right. Sorry for not looking into the error close enough before reporting.
