### ISSUE TITLE
Citation in margin

### ISSUE THREAD

**Issue by jhillairet** [fmarotta/kaobook#15]
Hello,

Many thanks for your work. I'm using kaobook, and it's more a question than an issue :

I would like to that the citations in the margin appear as _Author (Date)_, with the citation style as _numeric_ (`citestyle=numeric-comp`, leading to  [1], [5-8]). So, I've modified the kaobiblio.sty to

```
% Command to format the marginnote created for cited items
\NewDocumentCommand{\formatmargincitation}{m}{% The parameter is a single citation key
	\parencite{#1}: \citeauthor*{#1} (\citeyear{#1})\\%, \citetitle{#1}\\
}
```
which is fine. However, I would like to have the final reference as sorted (`sorting=nyt`). This leads to (as normal) to citation numbers following the alphabetical order, and thus citation numbers like: _[20, 3, 7]_ 

What should I do in order to put a citation number in the text like a footnote number (1, then 2, then 3, etc), keeping the \sidecite behaviour?

ex: 

```
-----text part---------                                     --------- margin -----------
blabalalala 1 blblbalal                                     1: Author1 (Date1)
blabla 2 blablabla                                           2: Author2 (Date2)
```
while keeping the reference alphabetically sorted ?

**Comment by fmarotta** [comment]
Thanks for reaching out. I am not sure I have understood the question fully, so let me ask you if this is what you need:

- In the main text, the citations should be sorted numerically (1, 2, 3...)
- In the margin, there should be the citations as normal in kaobook
- In the bibliography at the end, the references should not be numbered, but sorted alphabetically by author

Please let me know if this is indeed what you meant.

**Comment by jhillairet** [comment]
Yes that's it.

I have found some authors using numbered sidenotes. However the sidenotes
in kaobook are not numbered (is it possible?). It would be okay, even is
numbering restarts to 1 for each page.


Le dim. 20 oct. 2019 16:50, Federico Marotta <notifications@github.com> a
écrit :

**Comment by fmarotta** [comment]
Sorry for the lag.

In general, the citations in the text and in the bibliography follow the same sorting order, but it is possible to enforce two different orders using the so-called "refcontexts". After reading [these](https://tex.stackexchange.com/questions/244971/biblatex-order-of-entries-in-a-multi-citation) [three](https://tex.stackexchange.com/questions/361031/biblatex-how-to-automatically-sort-citation-by-year-sortcites-ynt-when-refere) [posts](https://tex.stackexchange.com/questions/162485/how-to-sort-in-text-citations-by-year-but-bibliography-by-name), I came up with the following piece of LaTeX, from which you can perhaps draw inspiration to edit your _main.tex_.

```
...

% Load the bibliography package and pass it some options
\usepackage[sorting=none,
            sortcites=true,
            citestyle=numeric-comp,
            bibstyle=authoryear]{styles/kaobiblio}
\addbibresource{book-template.bib}

% Use the "none" sorting for the document
\assignrefcontextentries[]{*}

% Redefine the citation style
\RenewDocumentCommand{\formatmargincitation}{m}{
    \parencite{#1}: \citeauthor*{#1} (\citeyear{#1})\\
}

...

\begin{document}

...

% Use the "nyt" sorting for the bibliography
\begin{refcontext}[sorting=nyt]
\printbibliography[heading=bibintoc, title=Bibliography] 
\end{refcontext}

...

\end{document}
```

Basically, for the main text we use sorting=none by specifying this as a global option, while for the bibliography we use sorting=nyt by encapsulating the \printbibliography command inside a refcontext environment. The result can be seen in the following figure:

![attachment1](https://user-images.githubusercontent.com/26001460/67422926-a5cb9d00-f5d3-11e9-9585-496e99bb51d1.png)


However, I have the doubt that you do not want the square brackets around the reference number. If this is the case, you will be able to use a superscript by redefining the citation style as in the following snippet, rather than as in the previous one:

```
% Redefine the citation style
\RenewDocumentCommand{\sidecite}{m}{
    \supercite{#1}
    \margincitation{#1}
}
\RenewDocumentCommand{\formatmargincitation}{m}{
    \supercite{#1} \citeauthor*{#1} (\citeyear{#1})\\
}
```

Finally, some remarks (you may as well skip this paragraph entirely). First of all, in theory you need not modify the _kaobiblio.sty_ package, but you should be able to do everything by passing options to it or by redefining some commands inside your _main.tex_, much like with any other package. Moreover, the `\sidenote`s in kaobook are numbered (see the documentation). Indeed, if you use both the sidenotes and the superscript instead of the square brackets, it may be quite confusing for your readers.

I hope this post will be helpful. Please let me know if you need a minimal working example or any further details! :)

**Comment by jhillairet** [comment]
Many thanks for that detailed explanation! I didn't know `\supercite` and the refcontexts. I also now pass the options directly from the master without modifying _kaobiblio.sty_. The result is looking the same as your example:

![image](https://user-images.githubusercontent.com/4642848/67467287-c8e46400-f648-11e9-8f0e-92678d683897.png)

As last minor things, is there a way to suppress the space between the `\sitecite{}` and the text after? I've tried removed trailing space or line returns in the command definitions, but without success.

**Comment by fmarotta** [comment]
Yes, the space after the `\sidecite` command is my fault: I forgot to add some `%` signs when I defined `\marginnote`, thanks for letting me notice this. The next commit will fix the problem and close this issue. (However, you will still need to add the `%` signs, or equivalently to remove the trailing space and newlines, after every line of the `\RenewDocumentCommand{\sidecite}` part. I have edited my previous comment to reflect this.)

By the way, if you also want to change the colour of the superscript, you can use, _e.g._,

```
\hypersetup{citecolor=black}
```

**Comment by jhillairet** [comment]
Thanks a lot. It works indeed with the latest version and proper `%` signs.
