### ISSUE TITLE
Sidecite overlap with Table caption

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fmarotta/kaobook#161]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

When using \sidecite next to a table, the caption of the table and the references overlap.

### Minimal Working Example
[You can use the following document to help you create a minimal working example.]
```
\documentclass{kaobook}
\usepackage[english]{babel}
\usepackage{blindtext}
\usepackage{kaobiblio}
\usepackage{kaotheorems}
\usepackage{kaorefs}


\begin{document}

\title{Bug Report}
\author{Author}
\date{\today}

\frontmatter

\KOMAoptions{twoside=semi}
\maketitle
\KOMAoptions{twoside=false}

\mainmatter
\setchapterstyle{kao}

\chapter{First Chapter}
\sidecite{hello, hello2, hello3}.
\begin{table} [ht]
    \centering
    \begin{tabular}{c c c}
        %\hline
        a & b & c\\
    \end{tabular}
    \caption{My long caption blablabla}
    \label{tab:my_tab}
\end{table}

\end{document}
```

**Expected behavior:** No overlap between the caption and the references

**Actual behavior:** 
![image](https://user-images.githubusercontent.com/40028739/124615596-b7230e80-de75-11eb-9dac-a500455feb59.png)

**Comment by AlexanderZeilmann** [comment]
Placing objects in the margin such that they do not overlap but still are close to their counterpart in the main body, is a hard and often impossible optimization problem.

I think the best solution is to manually adapt the placement of the `\sidecite` and the `\caption` once this is implemented.

Alternatively, you can rewrite the text a little bit. Instead of putting the sentence `These parameters are in good agreement with those used in [2-4]` above the table you could adapt the caption to something like `Parameters used for experimental validation. These parameters are in good agreement with those used in Hodille et al (2015), Bonnin et al. (2015) and Benannoune et al. (2019)`.

**Comment by fmarotta** [comment]
I fully endorse what @AlexanderZeilmann said. Sidenotes and sidecites don't overlap because they are all floating elements, but unfortunately, right now, captions in kaobook are controlled by the `float` package and it's very difficult to make `\sidecite` aware of them.

**Comment by RemDelaporteMathurin** [comment]
Thank you very much for your explanation! I shall close this issue.
