### ISSUE TITLE
List of listings

### ISSUE THREAD

**Issue by denniskb** [fmarotta/kaobook#173]
## Summary

Provide a list of listings similar to the already existing list of figures and list of tables.

**Comment by fmarotta** [comment]
Thanks for requesting this. The `listings` package already provided a list of listings through the command `\lstlistoflistings`; I have now customised the style of this list of listings so that it is similar to the existing list of figures/tables. Moreover, I added two aliases: `\listoflistings` and `\listoflstlistings`. Now any of these command will print a list of listings. I've also added an example in the documentation.
