### ISSUE TITLE
LaTeX Warning: Unused global option(s):     [fontsize=10pt,twoside=false].

### ISSUE THREAD

**Issue by goretkin** [fmarotta/kaobook#176]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Check that you are using the latest version of kaobook.
    * Check that your issue isn't already filed: https://github.com/fmarotta/kaobook/issues

### Description

Building the MWE gives
```
LaTeX Warning: Unused global option(s):
    [fontsize=10pt,twoside=false].
```

### Minimal Working Example
[You can use the following document to help you create a minimal working example.]
```
\documentclass[
	fontsize=10pt, % Base font size
	twoside=false, % Use different layouts for even and odd pages (in particular, if twoside=true, the margin column will be always on the outside)
]{kaobook}

\begin{document}
\mainmatter

\end{document}
```

**Expected behavior:** no warning
**Actual behavior:** the mentioned warning

similar: https://github.com/fmarotta/kaobook/issues/149

**Comment by fmarotta** [comment]
Thanks. The problem was caused by `\ProcessFamilyOptions` in *kaobook.cls*, that I used to process the `secnumdepth` option. Indeed, `\ProcessFamilyOptions` also deals with options declared with `\DeclareOption`, which in *kaobook.cls* were already processed by `\ProcessOptions`. Therefore, these class options were processed twice, leading to the warning. Now the "family options" are processed in *kao.sty*.
