### ISSUE TITLE
Subsection numbering

### ISSUE THREAD

**Issue by gsilano** [fmarotta/kaobook#21]
Hi @fmarotta! First of all, I would like to say thank you for your work. I'm using your template to write my doctorate thesis. So, my question: how I can number subsections too? I tried to have a look here, in the issues tracker, but I did not find what I was looking for. Also, I tried to manage the job myself, but it was not as easy as I thought.

Using the template I also discovered and fixed some problems with Biber (I use to write the bibliography using BibTeX). As soon as I finish the thesis, I will open a pull request with my changes. Then, you will decide if you want to keep them as a separate branch or merge in somehow in the repo.

In the meantime, thank for your time and help.

**Comment by fmarotta** [comment]
Hi @gsilano, thanks for using the kaobook! In order to number the subsections, you can just add

```
\setcounter{secnumdepth}{2}
```

to the preamble of your main.tex. More generally, by setting the counter to a different number you can choose the levels at which the numbering occurs. For instance, with secnumdepth=0 only parts and chapters are numbered. Just in case it may be helpful to you or somebody else, I put here the link to a useful documentation about section numbering: https://en.wikibooks.org/wiki/LaTeX/Document_Structure#Section_numbering.

As regards the bibliography, I'm looking forward to seeing your enhancements :) So far, I have considered only biblatex, so it will be nice to have bibtex support.

**Comment by gsilano** [comment]
Thanks for your help. As soon as possible, I will open a pull request with my changes.
