### ISSUE TITLE
Overlapping TODO, sidenote, sidetoc and sidecite

### ISSUE THREAD

**Issue by TheoWinterhalter** [fmarotta/kaobook#25]
It seems unfortunately that all these features (margin TODOs, sidenotes, side table of contents and side citations) do not always behave together.

In the `documentation` example, if I change the begging of `introduction.tex` with
```tex
\section{The Main Ideas}

\todo{This is a TODO}

Many modern printed textbooks have adopted a layout with prominent
margins where small\sidenote{A sidenote} figures\sidecite{Visscher2008,James2013}, tables, remarks and just about everything
```
The result (using one extra `pdflatex` invocation than the suggested compilation procedure) doesn't seem desirable.
<img width="903" alt="screenshot" src="https://user-images.githubusercontent.com/5960860/76153395-b6d10280-60cb-11ea-8278-c4ccb69cacb5.png">

As you can see, everything overlaps which is a bit sad. I expect this is going to be a tough one to solve though. But just in case.

**Comment by fmarotta** [comment]
Thanks for reporting this! As much as I tried to make everything automatic in the template, I don't think that it is possible to automatically position the elements in the margin. It would require knowing the height of each element, but the height is determined only at compilation time and it depends on the font and many other things. Even if we knew the height, we should dynamically position all the elements during the compilation, which I honestly wouldn't know hot to do. And even if I knew how to do it, the automatic result may not be aesthetically pleasing.

Thus, I believe that the best way to deal with this problem is that the author manually adjust the position of each element until he/she finds a satisfying configuration. The references and the sidenotes can be vertically shifted with an optional argument; the margintoc is best left where it is. The todo notes are, unfortunately, out of my control, but they should not appear in the final document anyway.

In fact, however, after writing a few documents in LaTeX I realised that at first it is best to just focus on the content, and only when every chapter has been written, to come back and adjust the layout. I hope that somebody proves me wrong and finds an easy way to automatically prevent the overlap of things in the margin, but until then, I'm afraid I will not work on this, sorry. Let me know if you need further guidance on the optional arguments to shift the sidecites, sidefigures, sidetables or sidenotes :)

**Comment by TheoWinterhalter** [comment]
Yeah I figures as much. I agree that for TODO it's not much of a problem.
I was indeed planning on tweaking those at the end, as is usual with LaTeX layout. :)
I still wondered if there was an automatic way since each package seems to know how to not overlap with itself.

Thanks.

**Comment by LaTeX-fetishist** [comment]
Am 20-03-08 um 09.02 schrieb Federico Marotta <notifications@github.com>:
> 
> As much as I tried to make everything automatic in the template, I don't think that it is possible to automatically position the elements in the margin. It would require knowing the height of each element, but the height is determined only at compilation time and it depends on the font and many other things. Even if we knew the height, we should dynamically position all the elements during the compilation, which I honestly wouldn't know hot to do.

You could simply use floats, here: marginpar.

> And even if I knew how to do it, the automatic result may not be aesthetically pleasing.

Margin columns shouldn’t be cluttered with lots of material, images, tables, whatever.  The main text should dictate the flow of reading; placing a significant amount of material parallel to the main text will hinder linear, meaningful reading more than pictures, tables or other flowing material at the top or bottom of the text.
Thus, if so much material appears in the margin column that it is no longer sensibly positioned automatically, then the margin column is probably already too full.
Marginal columns that are overfilled with notes, pictures, pictograms, etc. and perhaps with colour contrasts or borders are a bad habit that often is spotted in printed products produced with the usual DTP programs.  Such graphic noise makes the pages appear unclear and illegible and should be avoided.


Regards,

-Moss-
--
Martin Wilhelm Leidig

**Comment by TheoWinterhalter** [comment]
Oh I understand your point. However, it is enough to put a `sidenote` and a `sidecite` on the same line or close enough to have overlap, even if there is plenty of space.

**Comment by fmarotta** [comment]
Ahh, yes, @LaTeX-fetishist is right, I could use floats. Now the template actually relies on two different packages, sidenotes and marginnotes, and maybe they do not play well with each other. There is also another concern: in the template the position of sidenotes and marginnotes was adjusted  so as to be aligned with the lines of the main text; is it possible to do the same with floats?

Anyways, I now see this as a weakness of the template, but I'm afraid that in order to fix it the code for `\sidenote`, `\marginnote`, and others must be rewritten from scratch... I'll try to think about it.

**Comment by fmarotta** [comment]
OK, I finally tried to work on this issue... now `\sidenote`s, `\marginnote`s and `\sidecite`s are defined as floating elements if the offset is not specified (but if the offset is specfied, they don't float), so now they shouldn't overlap anymore. I couldn't do anything about the `\margintoc`, which therefore remains non-floating. I am closing this issue but I'll leave the help-wanted label: if someone figures out how to make the margintoc float, I shall be very glad.

**Comment by TheoWinterhalter** [comment]
Thanks a lot for doing this!

**Comment by sergiogf93** [comment]
Hi @fmarotta, I am having this issue about the overlapping citations. I am not super familiar with using this template, but it sounds like a workaround was found for it? Could you provide an example on what can be done to modify the vertical alignment of the citation? Maybe it's something very easy, like adding an argument to sidecite but I don't know what to do.
