### ISSUE TITLE
Citations have space after them

### ISSUE THREAD

**Issue by TheoWinterhalter** [fmarotta/kaobook#26]
Whenever I use `\sidecite` before a punctuation mark like a point or a comma, there is a space before it.
![space before bracket](https://user-images.githubusercontent.com/5960860/76771436-a1309c80-679f-11ea-9a0e-30d29c68f1c2.png)
This is a minor detail but it's bugging me. I am using the `\sidecite` command wrong somehow?

**Comment by fmarotta** [comment]
Sorry to hear this. In one of yesterday's commits I should have fixed it -- the problem was a missing % sign. Can you confirm that you are using the latest version of the template? Anyways, if you don't want to update, or if you are using the template from latextemplates.com, the following image shows how to fix the problem. (the file to edit is `styles/kaobiblio.sty`)
![image](https://user-images.githubusercontent.com/26001460/76773866-73e5ed80-67a3-11ea-98af-825d78a96eea.png)

**Comment by TheoWinterhalter** [comment]
Ah sorry, I was indeed not using the latest version.
It now works perfectly, thanks a lot!
