### ISSUE TITLE
References to part use wrong numbering

### ISSUE THREAD

**Issue by TheoWinterhalter** [fmarotta/kaobook#29]
When parts aren't numbered (which is the default with kaobook), references to parts are partly wrong. It seems they will use the number of the preceding section instead (in my cases it write `Part 10.3`since the part follows chapter 10 which has 3 sections). The hyperref, name and page are all correct though.
I expect it's just a matter of counter.

**Comment by fmarotta** [comment]
Sorry for the lag, and nice catch! Even in other LaTeX classes, it is not possible to use `\ref` on an unnumbered section, chapter or part; the problem is that, in kaobook, the handy `\refpart` command secretly calls `\ref`... Labels must be "anchored" to a numbered element, therefore unnumbered parts are completely ignored, causing the label to anchor to the closest numbered section upstream of the part. Packages such as `nameref`, which are also used in kaobook, can overcome the problem, but I could not find a way to check whether the part being referenced is numbered or not in order to automatically choose whether to use `\ref` or `\nameref`. However, I added two new referencing commands: `\arefpart` and `\avrefpart`. The idea is that the writer should know if the parts are numbered or not in his or her document, and can choose the most appropriate command accordingly, just like he or she can choose each time whether to use `\refpart`, `\vrefpart`, `\nrefpart` or `\frefpart`. In particular, `\arefpart` writes references such as: `Part 'Name of the Part'`, whereas `\avrefpart` writes also the page, as for instance in: `Part 'Name of the Part' on page 84`. The initial 'a' should remind of `\addpart`, used to add an unnumbered part, and of asterisk, a symbol that can also be used to insert unnumbered sections or parts.

**Comment by TheoWinterhalter** [comment]
Thanks! It seems fair to assume the user knows whether they're using numbered parts or not.

**Comment by flimzy** [comment]
I've run into this same issue. How do I enable numbered parts?

**Comment by fmarotta** [comment]
To insert a numbered part, don't write `\addpart{Title of the part}`, but rather `\part{Title of the part}`.

If instead you wanted to use the new `\arefpart` command but couldn't find it, then you will have to update your template to a newer version. If you are using GitHub you can download the repository again; if you are using Overleaf through latextemplates.com, then you can edit the file `styles/kaorefs.sty` and add yourself the definitions of these commands (you can find the definitions in the file `styles/kaorefs.sty` in this repository).

**Comment by flimzy** [comment]
> To insert a numbered part, don't write `\addpart{Title of the part}`, but rather `\part{Title of the part}`.

Thank you very much!  `\part` was the piece missing for me.
