### ISSUE TITLE
How to remove the space after a citation 

### ISSUE THREAD

**Issue by thomneos** [fmarotta/kaobook#41]
Dear Federico, 
I have been using your fantastic template for the last months to write my thesis, I wanted to thank you very much, I love it ! 
I managed to modify everything I wanted to change in your template, but there is just one point I could not solve :
there is always a space after the citation, i.e. my output looks like _[33] blabla_ and I would like to have by default _[33]blabla_. Can you help me ??
Thank you again !

**Comment by fmarotta** [comment]
Thank you! Yes, unfortunately there was a bug which now has been fixed in the GitHub version, but not yet in the Overleaf version. So if you downloaded the template from GitHub, simply updating the repository, or downloading it again, will solve the problem (but may also result in other issues). If you use Overleaf or if you prefer not to download the whole template again, you can fix the problem yourself by editing the `styles/kaobiblio.sty` file and adding a '%' sign after every line in the definitions of the commands `\margincitation` and `\formatmargincitation`, as illustrated in the picture below:

![image](https://user-images.githubusercontent.com/26001460/85629067-793fb780-b671-11ea-91e8-37b729515e32.png)

**Comment by bradyneal** [comment]
@fmarotta I'm guessing this is not actually fixed in the current GitHub version, since you've left this issue open. Is that correct? I seem to be having this issue, and I'm pretty sure I'm using the current GitHub version.

**Comment by fmarotta** [comment]
Ahh, sorry, it was fixed, but then recently I accidentally reintroduced the bug when I edited the `kaobiblio` package. The problem were again the missing `%` at the end of the lines in the macros. The next commits will fix the issue and close it (I left it open because I was waiting for the OP's feedback). Thanks for letting me know.

**Comment by bradyneal** [comment]
Gotcha. Thanks for the re-fix! I confirm that it is working for me.
