### ISSUE TITLE
Recommended workflow for easily integrating kaobook repo updates

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#45]
Is there a recommended workflow for easily pulling in new commits from `fmarotta/kaobook` to our personal git repos that we use for our books? For example, I'm currently considering `git remote add kaobook git@github.com:fmarotta/kaobook.git` and then doing some sort of `git pull kaobook` type thing.

**Comment by fmarotta** [comment]
This is exactly what I do. As an alternative, if you are writing many books at the same time, you could clone the repository in your TEXMFHOME (see [here](https://github.com/fmarotta/kaobook/blob/master/instructions/texlive_integration/README.md) for instructions), so that you have to pull the changes only once for all of your books, and you don't even need to have the `kaoobook.cls` and `styles/*` files in the same folder as your book.

PS
I plan to upload the class on CTAN next month. But even then, in order to have the latest possible version, the git remote add solution should work best.

**Comment by bradyneal** [comment]
> if you are writing many books at the same time

😅 🚀

> I plan to upload the class on CTAN next month.

Brilliant. Though, yeah, it will still be useful to be used to the remote repo workflow.
