### ISSUE TITLE
textcite-like functionality with sidecite

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#46]
Is there a way to get `\textcite`-like functionality with the `\sidecite` command? For example, say I want to reference the author's name in the text and have the citation information in the margin. I'm currently using `\authorcite{x} \sidecite{x}` to get the desired functionality. Is this how textual citations are intended to be done in the kaobook package, or is the plan to add additional \sidecite options or commands to get this functionality in a single command?

**Comment by fmarotta** [comment]
Good question. First of all, you can pass to the `kaobiblio` package all the options that you can pass to the `biblatex` package (e.g. `\usepackage[style=authoryear,backend=bibtex]{kaobiblio}`). With these options you can change the style of the citation marker in the text body and in the bibliography at the end (by default it is numeric, like [1], [2], and so on).

Secondly, you can redefine the `\formatmargincitation` command to choose what is displayed in the margin. By default we have
```
\NewDocumentCommand{\formatmargincitation}{m}{% The parameter is a single citation key
    \margincitedelim\parencite{#1}: \citeauthor*{#1} (\citeyear{#1}), \citetitle{#1}%
}
```
Where `\margincitedelim` is the delimiter for when multiple documents are cited at the same time (by default, `\\`).

If one is not able to achieve what he or she wants with a combination of the above methods, then they could always define their own macro. In your case, the `style=authoryear` option could be what you were looking for, otherwise you could for instance define
```
\newcommand\authorsidecite[1]{\citeauthor{#1} \sidecite{#1}}
```

**Comment by bradyneal** [comment]
Hmm, gotcha. I think that means that I'll stick with that last thing you mention to emulate `\textcite` with the mini citation in the margin: `\newcommand{\authorsidecite}[1]{\citeauthor{#1} \sidecite{#1}}`.

**Comment by fmarotta** [comment]
All right then!

**Comment by bradyneal** [comment]
See #50 for the added functionality in the new `\sidetextcite` and `\sideparencite` commands that mirror `\textcite` and `\parencite`.

**Comment by smetzler** [comment]
Hi, I very much like this new feature. In fact, I had my own (somewhat more primitive) definition of a \sidetextcite before, and just now started to switch to yours. It seems worth it, since I noticed that the placement of the margincitations now significantly improved: There is no need manually shift them around anymore, so that they don't overlap. 

The question I have is regarding this plavement. So, I hope this is the correct issue to post it. Please tell where else to look, otherwise.

I'm having a page where the margin is filled with one sidenote at the top and lots of margincitations thereafter. The alignment is all fine, i.e. citations occur right next to their mentioning in the text, whenever possible, sometimes a bit further down, when the space was already taken. Now, I want to additionally cite a paper within the sidenote. 
Expected outcome: the additional citation shows under the sidenote. The positions of the remaining citations remain unaffected as much as possible. 
Observed outcome: the additional citation takes the place of the formerly first citation on the page, causing a shift of every citation to the next position. The original positioning however is kept, such that now citation x is displayed next to the mentioning of citation x+1 in the text. The last citation of the page is even pushed to the following page.
How do I prevent this?

**Comment by bradyneal** [comment]
Responded in #67

**Comment by fmarotta** [comment]
Thank you, let us continue the discussion in #67
