### ISSUE TITLE
Reusing the same figure mutliple times with the same figure number

### ISSUE THREAD

**Issue by bradyneal** [fmarotta/kaobook#69]
I like to redisplay relevant content (mainly equations and figures) whenever I bring it up again and the previous time it appeared isn't on that page. This seems especially attractive for tufte-style templates with the big margin because the margin is there; might as well use it.

This is relatively easy to do with equations. This [Stackoverflow answer](https://tex.stackexchange.com/a/225075) gives a way to do this with regular figures, but I couldn't figure out how to get it working with marginfigures. Any chance you could look into this or guide me a bit on how I might do this?

**Comment by fmarotta** [comment]
Sorry for the late reply. Here's what I came up with, inspired by the answer you linked:
```
\makeatletter
\NewDocumentEnvironment{sourcemarginfigure}{o}{%
    % Renew the \label command to save the label of the figure
    \let\oldlabel\label%
    \RenewDocumentCommand{\label}{m}{%
        \gdef\sfname{sf:##1}%
        \oldlabel{##1}%
    }%  
    \marginskip{\kaomarginskipabove}%
    \begin{lrbox}{\@sidenotes@marginfigurebox}%
        \begin{minipage}{\marginparwidth}%
            \captionsetup{type=figure}%
}{%
        \end{minipage}%
    \end{lrbox}%
    \IfNoValueOrEmptyTF{#1}%
    {\marginnote[0pt]{\usebox{\@sidenotes@marginfigurebox}}}%
    {\marginnote[#1]{\usebox{\@sidenotes@marginfigurebox}}}%
    \marginskip{\kaomarginskipbelow}%
    % Copy the current box holding the minipage into a new box
    \global\expandafter\newsavebox\csname \sfname savebox\endcsname%
    \global\setbox\csname \sfname savebox\endcsname=\copy\@sidenotes@marginfigurebox%
}

\NewDocumentCommand{\reusemarginfigure}{o m}{%
    \renewcommand{\theHfigure}{dupe-fig}% If you're using hyperref
    \renewcommand{\label}[1]{}% Make \label inactive
    \IfNoValueOrEmptyTF{#1}%
    {\marginnote[0pt]{\usebox{\csname sf:#2savebox\endcsname}}}%
    {\marginnote[#1]{\usebox{\csname sf:#2savebox\endcsname}}}%
}

\makeatother
```

Add the above to the preamble of the main.tex, and use it as described in the stackoverflow answer, except that the commands are now source*margin*figure and \reuse*margin*figure. the `sourcemarginfigure` environment is exactly equal to the `marginfigure` environment from the point of view of the user. The `\reusemarginfigure` command takes one optional argument, the vertical offset, and one mandatory argument, the label of the source figure.

Tip: if you use \labfig instead of \label, when you call `\reusemarginfigure` pass it "fig:label" as a label, instead of the raw label. E.g. if you have
```
\begin{sourcemarginfigure}
\includegraphics{...}
\labfig{myfigure}
\end{sourcemarginfigure}
```
then call
```
\reusemarginfigure{fig:myfigure}
```
