### ISSUE TITLE
Undefined control sequence \mainmatter

### ISSUE THREAD

**Issue by Firionus** [fmarotta/kaobook#74]
I tried to compile `book-template.tex` today, but could not get rid of the error: 
 ```
! Undefined control sequence.
<write> 
Class \KOMAClasSName 
                               Warning: Usage of deprecated command `\string...
l.198 \mainmatter
                  % Denotes the start of the main document content, resets p...
```
For full log see this gist: https://gist.github.com/Firionus/7de9836e709ebc7b0fb1e71aedd1f566

I'm using  a fresh TeXLive install on Xubuntu 20.04 via tl-install. It's has some collections installed, but far from a full install. Kaobook was freshly cloned from Github, though downloading from LaTeX Templates gives the same result. 

I'm stumped why the compiler doesn't recognize the redefinition of `\mainmatter` in `kaobook.cls`. While I'm not completely helpless with computers, LaTeX is its own beast, so I'd appreciate any help you can offer.

**Comment by AlexanderZeilmann** [comment]
The problem is not `\mainmatter` but `\KOMAClasSName` which should be `\KOMAClassName` (with lower case `s`).
This is a bug in KOMAScript which was introduced in a recent version.

A quick fix would be to
* go to the folder where the LaTeX packages are installed on your computer,
* open it in a text editor,
* search globally for `\KOMAClasSName` (this should result in something like the image below),
* replace all occurrences it with `\KOMAClassName`,
* done.

I hope this helps, it worked for me.

![Bildschirmfoto 2020-09-12 um 10 40 12](https://user-images.githubusercontent.com/901391/93181192-73211a80-f738-11ea-97d1-2a4aa49a794f.png)

**Comment by Firionus** [comment]
Oh, yes, that seems to be it. 

My buggy version was `cat-version: 3.31`. I updated to the latest koma-script by following https://komascript.de/node/2049. Now I'm at `cat-version: 3.32.3541` and the problem is gone - book-template.tex compiles just fine! Thanks a lot. 

How you guys do this in your free time without dependency management is a mystery to me...
