### ISSUE TITLE
Items in LoF is incorrectly placed due to marginfigure

### ISSUE THREAD

**Issue by hCarlFelix** [fmarotta/kaobook#77]
I've encountered a problem similar to #34 in that marginfigures can get incorrectly placed in the LoF as shown below

![LoF_example_error](https://user-images.githubusercontent.com/55991448/96149769-fb4a3980-0f09-11eb-948f-18f37ad5c45a.png)

This problem occurs if the offset of the marginfigure is not specified. A potential fix is to add a default value to the offset, changing the current definition of marginfigure:
```
\RenewDocumentEnvironment{marginfigure}{o}{%
  \marginskip{\kaomarginskipabove}%
  \begin{lrbox}{\@sidenotes@marginfigurebox}%
	\begin{minipage}{\marginparwidth}%
	  \captionsetup{type=figure}%
}{%
    \end{minipage}%
  \end{lrbox}%
  \marginnote[#1]{\usebox{\@sidenotes@marginfigurebox}}% Place the table box in the margin
  \marginskip{\kaomarginskipbelow}%
}
```
into something like
```
\RenewDocumentEnvironment{marginfigure}{o}{%
  \marginskip{\kaomarginskipabove}%
  \begin{lrbox}{\@sidenotes@marginfigurebox}%
	\begin{minipage}{\marginparwidth}%
	  \captionsetup{type=figure}%
}{%
    \end{minipage}%
  \end{lrbox}%
  \IfNoValueOrEmptyTF{#1}%
    {\marginnote[0pt]{\usebox{\@sidenotes@marginfigurebox}}}%
    {\marginnote[#1]{\usebox{\@sidenotes@marginfigurebox}}}%
  \marginskip{\kaomarginskipbelow}%
}
```

[A MWE showing the LoF error](https://github.com/fmarotta/kaobook/files/5385998/LoF_example_error.zip)

**Comment by fmarotta** [comment]
Thanks, I did exactly as you suggested.

**Comment by fmarotta** [comment]
Wait, this way we lose the automatic placing of marginfigures so that they don't overlap, which worked only because they were floating. I think this problem is harder than it looks... LaTeX ensures that floats belonging to the same class (e.g. figure) are typeset in the order in which they are called, but marginfigures, relying on \marginpar, are not of class "figure". I tried to understand how to set the class of marginpars to "figure", but couldn't find a way. The best I could do is to (a) use the `scrhack` package, which removes the vertical white space after marginfigures in the list of figures, and (b) add `\FloatBarrier` automatically before each marginfigure so that all floats preceding the marginfigure are processed. I'll add the help-wanted tag to this issue to attract the experts.

**Comment by fmarotta** [comment]
Hi apparently the package `marginfix` was responsible for this problem as well... (it was also causing #169)

Now that I've removed this package, the entries are properly aligned. Please download the latest version and try again :)
