### ISSUE TITLE
Change mathalfa package to mathalpha

### ISSUE THREAD

**Issue by agnel** [fmarotta/kaobook#8]
The mathalfa package has been renamed to mathalpha. Kindly please update this in the style.sty

**Comment by fmarotta** [comment]
Hello, thanks for reporting this.

At the moment, if I change the package name, the compilation fails with an error both on my local machine and on Overleaf; could it be that the new version of the package has not been included in all LaTeX distributions? Anyway, [it seems](https://ctan.org/tex-archive/macros/latex/contrib/mathalpha?lang=en) that the package will work under both names.

Have you been experiencing troubles because of the name of this package? If so, I'd like to have some additional details, like how the document was compiled, the name and version of your LaTeX distribution (if any), if you have downloaded the mathalpha package directly from CTAN and possibly a minimal working example.

Thank you for your interest and your collaboration.
Federico

**Comment by agnel** [comment]
Thank you for your reply.

Yes as per the package details mentioned on the CTAN. It will work for both
names. As they have kept it for backwards compatibility.

If you are still facing this issue, then you need to refresh the
repository, and the package will be listed, which you can install. By
default when you build the kaobook first time it will try to fetch the
mathalfa package, but since the link doesn't exists anymore, it will fail
again and again. As a remedy you need to update the name in code as
mathalpha.

For me initially the new package name was not listing, but after refresh it
showed up and I installed it, then I changed the name to mathalpha in code.


Thank you,
Agnel

**Comment by fmarotta** [comment]
I see your point and I reckon that in the long run changing the name would be the right thing to do. My only concern, and I have it only because of my lack of knowledge, is that I can't figure out how many people would be affected by the problem you reported, because for instance both on Overleaf and on my laptop with Arch Linux, the compilation works with the old _mathalfa_ but fails with _mathalpha_.

If you agree, I will wait to change the name of the package until at least Overleaf understands the new name. If someone else has this problem, however, please report it here so that I can fix the name immediately. Meanwhile I'll leave this issue open, so that people with the same problem can find it and use your solution.

**Comment by fmarotta** [comment]
Closing the issue as `mathalpha` still does not work for people that use Overleaf.
