### ISSUE TITLE
overlapping marincitations

### ISSUE THREAD

**Issue by yordiak** [fmarotta/kaobook#83]
Hello,

The following image illustrates my problem

![image](https://user-images.githubusercontent.com/21086323/99901249-de014b80-2cbd-11eb-8586-8549fd3741d1.png)

As you can see there is an overlap between two different side citations. Probably the solution is to change some parameters but I dont know where to look for

PS: I am using an older version of this template.

**Comment by fmarotta** [comment]
Hmm, I see. The problem should be solved in recent versions, but maybe you can still fix the overlap yourself by passing an option to `\sidecite` specifying the vertical shift, e.g. `\sidecite[2mm]{Nyborg2016}`. If this doesn't work because your version is too old, I think it's safe to just replace your `kaobiblio.sty` with the latest one.
