### ISSUE TITLE
Can I render a book in landscape orientation?

### ISSUE THREAD

**Issue by cyberglot** [fmarotta/kaobook#85]
I'm writing a book in kao and I'd like to generate a version of the book for desktop and tablet reading in landscape. If it's not a thing that can be easily implemented, how much effort would it take?

**Comment by fmarotta** [comment]
Hi, yes, it should be easy enough because the class has a way to globally choose a scale for the horizontal and a scale for the vertical dimensions. In the latest commit, I have made some stylistic enhancements and I have added the "a4paperlandscape" option as a proof of concept.

If you are OK with the A4 paper size, you can just download the latest from GitHub and make sure that the first line of the main.tex reads something like:
```
\documentclass[a4paperlandscape]{kaobook}
```

Otherwise, the easiest thing would be to implement another option for the paper size that you require; if you send me the the dimensions of the paper I can do that. You can also do it yourself taking inspiration from the "a4paperlandscape" option defined at line 115 of the file `styles/kao.sty`.

**Comment by cyberglot** [comment]
Oh, Thank you. A4 works for me just fine.
