### ISSUE TITLE
Confused about versions

### ISSUE THREAD

**Issue by flimzy** [fmarotta/kaobook#87]
I was excited to see [a new version](https://github.com/fmarotta/kaobook/releases/tag/0.9.0) of this out, so I downloaded it to see what's new, and was struck by:

```diff
-Copyright 2020 Federico Marotta
+Copyright 2019 Federico Marotta
```

and

```diff
-% Version 1.2 (4/1/2020)
+% Version 0.9 (2020/12/02)
```

Is this "new" 0.9 just tagging an old release?  Or did I somehow fetch some other/unofficial/forked version 1.2 before from somewhere?

**Comment by fmarotta** [comment]
Sorry, the versioning of this project has been confusing since the beginning... See also #62. Because of that, I decided to 'start from scratch' and make a first official release here on GitHub. In the past I have often been careless and I haven't always properly incremented the version, so many users complained about the misunderstandings that stemmed from the many different and incoherent versions (for instance, at some point almost every file had a different version). For this reason, I consider all the versions previous to the one on GitHub as 'unofficial.' Now I am trying harder to stick to a strict release scheme, and I have started by assigning one single version to the whole project, instead of to each file. The "copyright 2019" is an error that I didn't notice, thanks for letting me know.

**Comment by flimzy** [comment]
Thanks for the explanation!

**Comment by LaTeX-fetishist** [comment]
Hi Federico,

on 20-12-08 21.08 you wrote:
> 
> The "copyright 2019" is an error that I didn't notice, thanks for letting me know.

Maybe you should think about unification of all of those part files, substyles, etc. into one documented TeX file (DTX) so that you only have to change administrative information and other things that are the same in all shares once.  Please see <https://www.ctan.org/pkg/doc> and <https://www.ctan.org/pkg/docstrip> (and <https://www.ctan.org/topic/doc-supp>) for that.  Scott Pakins tutorial <https://www.ctan.org/pkg/dtxtut> is a good read on that.

This can also be combined with the automatic insertion of the corresponding git hash value.  There are a few packages for that; I frequently use gitinfo <https://www.ctan.org/pkg/gitinfo2> but there are others (<https://www.ctan.org/topic/version-control>, <https://www.ctan.org/topic/doc-mgmt>).

As far as my free time(*) allows I’d help in that.  To be honest, I was toying with the idea of forking kaobook and just doing the above on my own, but, you know ... sorry, but that will take a while.


(*) Disclaimer:  As you will know we have some Corona-SARS2/CoVid19 problems over here, and my wife runs a home care service where I support her as far as I can.  We'll see how this develops over the holidays (and afterwards).

Stay well, please.


Regards,

-Moss-
--
Martin Wilhelm Leidig
Dante Member #1580

**Comment by fmarotta** [comment]
Many thanks. Making a package for CTAN has been in my thoughts for quite some time now, but so far I have never found the time to read the documentation and create the DTX. I guess now I'll start by checking out the links you sent. Your help would be appreciated, but of course health and family are more important :)
