### ISSUE TITLE
Compatibility with Valbusa's biblatex-phylosophy? 

### ISSUE THREAD

**Issue by Giordane86** [fmarotta/kaobook#9]
Ciao!
To facilitate the use of your template among Italian users, in particular the "humanists", are you planning to integrate the Valbusa's bundle (biblatex-phylosophy) into kaobook?

**Comment by fmarotta** [comment]
Ciao,

It seems a good idea, in the next days I will work on making it easier to change the language and the bibliography style, also allowing to use the biblatex-philosophy bundle :)

At the moment you could open the kaobook.cls file, find the place where biblatex is loaded and customise its options, in particular you may want to add the option "style=philosophy-<style>" and comment out the "bibstyle" and "citestyle" ones. In this way you will be able to use biblatex-philosophy right away. (However, don't expect the citations in the margins to work!)

**Comment by Giordane86** [comment]
That would be great! 
Tank you!

**Comment by fmarotta** [comment]
Here I am! To sum up the changes I made so far,

- The document language can now be chosen from the main.tex file by loading the babel package;
- All the options that are passed to biblatex can be chosen (in particular you can easily use biblatex-philosophy);
- The format of the margin citations can be edited, so that their style can agree with that of the rest of the bibliography;
- The section about the bibliography in the example book has been expanded to take into account the above changes.

So from now on, if you want to use the new features, the only thing that you should do is to load the 'styles/kaobiblio' package in the preamble of your document. When you load it you can pass to it all the options you would normally pass to biblatex. For instance,

```
\usepackage[style=philosophy-verbose]{styles/kaobiblio}
\addbibresources{main.bib}
```

Then, if you also want to use the margin citations, you may want to change their format by 'renewing' the \formatmargincitation command. Basically, this command accepts one argument, the citation key, and prints directly into the margin whatever you want. Perhaps the following definition could be satisfactory for a biblatex-philosophy style:

```
\renewcommand{\formatmargincitation}[1]{
    \sdcite{#1}
}
```

(See chapter 5 of the example book for a more complete discussion.)

Let me please know if this met your expectations or you wanted some more features.

Best,
Federico

**Comment by Giordane86** [comment]
Hi Federico.
It seems like a great job. I'm sure it will facilitate the use of your template among Italian users.
As for me, to remedy the problem (pending your latest changes), I modified the bibliographic style by acting, as you suggested, on the .cls file; and to get the quotations in the margin I have used, from time to time, the command /sidenote together with /cite.
Thanks again for these latest implementations!
