### ISSUE TITLE
Table caption for a wide table is too narrow

### ISSUE THREAD

**Issue by mberth** [fmarotta/kaobook#95]
I'm trying to produce a wide table:

```tex
\documentclass[oneside]{kaobook}
\usepackage{blindtext}
\begin{document}

\begin{longtable}{lp{8cm}p{6cm}p{2cm}}
NR & Column 1         & Column 2  & Column 3 \\
\hline \\
   & \textbf{Heading} &            & \\
1  & \blindtext       & \blindtext & rest \\
\hline
\caption{\label{tbl:xxx} The caption is: \blindtext}
\end{longtable}

\blindtext

\end{document}
```

The table itself looks ok (i.e. it extends into the margin). However, the caption looks odd, I'd expect it to start at the left margin of the main text and extend into the right margin, just like with a wide figure. BTW, I've tried to use `\begin{table*}...\end{table*}` but that resulted in "Misplaced alignment tab character &".

![Bildschirmfoto 2020-12-21 um 13 30 40](https://user-images.githubusercontent.com/77945/102777490-f2a23380-4390-11eb-8980-2773a988506a.png)

**Comment by fmarotta** [comment]
The "Misplaced alignment tab character &" occurs when one uses the syntax:

```
\begin{table*}{lp{8cm}p{5cm}p{2cm}}
...
\end{table*}
```

while the correct syntax is

```
\begin{table*}
    \begin{tabular}{lp{8cm}p{5cm}p{2cm}}
    ...
    \end{tabular}
    \caption{...}
\end{table*}
```

As regards long tables, there were actually two problems, the first being that the caption was not properly left-aligned, and the second being that the caption did not have the right length. I made a small change in the file `styles/kao.sty` so as to fix the alignment problem, but I am not sure that increasing the width of the caption would be a good idea, because if one has a small longtable that does not extend into the margin, it would probably be best to have a narrow caption as well. So I found a workaround to increase the width of the caption only for tables that extend into the margin, and it involves writing two additional commands, one before and one after the longtable:

```
\floatsetup[longtable]{margins=centering,LTcapwidth=table} % Add this line before the longtable to increase the caption width
\begin{longtable}{lp{8cm}p{5cm}p{2cm}}
...
\end{longtable}
\floatsetup[longtable]{margins=raggedright,LTcapwidth=\textwidth} % Add this line after the longtable to revert the previous change
```

![image](https://user-images.githubusercontent.com/26001460/102918302-f617e680-4486-11eb-9fc6-f3390f65e6c0.png)

In the end, however, I would suggest to always use the table* environment for wide tables.
