### ISSUE TITLE
Error generated by mdftheorems.sty

### ISSUE THREAD

**Issue by jhsh** [fmarotta/kaobook#96]
Hi Federico

I use a fully up-to-date MikTeX under Windows 10 with the latest kaobook (pulled today). When compiling main.tex I get the following error from mdftheorems.sty:

! Missing \endcsname inserted.
<to be read again> 
                   \opt@styles/mdftheorems.sty 
l.60 \ProcessOptionsX\relax

If I comment out l.60 the compilation completes without further errors (and the resulting doc is identical to yours, except for an additional page 43 with an Alphabetical Index).

I find l.57: \DeclareOption*{\PassOptionsToPackage{\CurrentOption}{biblatex}} strange. There are no Options declared (only OptionsX) and even if there were why pass them to biblatex? I am probably missing something, but am mystified nevertheless.

Happy New Year and continue the good work!
Jannie Hofmeyr

**Comment by jhsh** [comment]
Yesterday I pulled a fresh copy of kaobook, made sure MikTeX was up to date, refreshed the filename database and recompiled main.tex. This time there were no errors, so I don't know what went wrong previously. This issue can be therefore be closed, but I did pick up an ifthispageodd which should be Ifthispageodd  (capitalised "I" ) in l.74 of kaobook.cls.

**Comment by Astroprog** [comment]
I encountered exactly the same issue as described above with texlive under linux and the current git repository.

**Comment by fmarotta** [comment]
Hi, I have now switched to package `kvoptions` to handle key-value options. The issue seems to be solved and the options to `mdftheorems` work as expected: one can change the background of all types of theorems at the same time (with the option 'bakcground=\<colour\>'), or change the background of individual types of theorem (with, e.g., 'remarksbackground=\<colour\>'), overriding the default.

**Comment by jhsh** [comment]
Excellent! Thanks Federico.
